spring:
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: true
        properties:
            hibernate:
#                show_sql: true
#                format_sql: true
                default_batch_fetch_size: 100

logging:
    level:
        org.hibernate.SQL: debug
        hibuy.server: debug

server:
    error:
        include-stacktrace: never
#        include-message: never
#        include-binding-errors: never

kakao:
    oauth2:
        redirect_uri: ${KAKAO_REDIRECT_URI}
        client_id: ${KAKAO_REST_API_KEY}
        client_secret: ${KAKAO_CLIENT_SECRET}